name: Release

on:
    push:
      tags:
        - 'v*' # Trigger the workflow on tag pushes that match the pattern 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build JAR
        run: mvn package

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: release-notes.txt
      
      - name: Extract Tag Name
        id: extract_tag_name
        run: echo "TAG_NAME=$(echo "${{ github.ref }}" | cut -d '/' -f 3)" >> $GITHUB_ENV
      
      - name: Upload JAR and Properties
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            ./target/jmeter-har-import-plugin-local.jar
          asset_name: |
            jmeter-har-import-plugin-${{ env.TAG_NAME }}.jar
          asset_content_type: application/java-archive
      
