name: Release

on:
  push:
    tags:
      - 'v*' # Trigger the workflow on tag pushes that match the pattern 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build JAR
        run: mvn package

      - name: Read Release Notes
        id: release_notes
        run: echo "::set-output name=notes::$(cat release-notes.txt)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.release_notes.outputs.notes }}

      - name: Upload JAR
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/jmeter-har-import-plugin-local.jar
          asset_name: jmeter-har-import-plugin-${{ github.ref }}.jar
          asset_content_type: application/java-archive
