name: Release

on:
  push:
    tags:
      - 'v*' # Trigger the workflow on tag pushes that match the pattern 'v*'

permissions:
  contents: write
  issues: read
  checks: read
  pull-requests: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          echo "DISPLAY=:99.0" >> $GITHUB_ENV
          sleep 5 # Wait for Xvfb to start

      - name: Build JAR
        run: mvn package

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: release-notes.txt

      - name: Extract Tag Name
        id: extract_tag_name
        run: |
          RAW_TAG=$(echo "${{ github.ref }}" | cut -d '/' -f 3)
          TAG_NAME=${RAW_TAG#v}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Upload JAR and Properties
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            ./target/jmeter-har-import-plugin-local.jar
          asset_name: |
            jmeter-har-import-plugin-${{ env.TAG_NAME }}.jar
          asset_content_type: application/java-archive
  
